package net.shushi93.resource.client.util;

import net.minecraft.client.Minecraft;
import net.shushi93.resource.ResourceScreening;
import org.slf4j.LoggerFactory;

import java.io.FileOutputStream;
import java.nio.file.Path;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public class Pack_Creator {

    public static void createPack(String pack_name) {
        Path pack = Minecraft.getInstance().gameDirectory.toPath().resolve("resourcepacks").resolve(pack_name + ".zip");

        try (ZipOutputStream zos = new ZipOutputStream(new FileOutputStream(pack.toFile()))) {
            zos.putNextEntry(new ZipEntry("pack.mcmeta"));
            zos.write("""
                    {
                      "pack": {
                        "description": "Generated by resource-screening for custom textures",
                        "min_format": [69, 0],
                        "max_format": [2147483647, 0]
                      }
                    }
                    """.getBytes());
            zos.closeEntry();
        } catch (Exception e) {
            LoggerFactory.getLogger(ResourceScreening.MOD_ID).error("Failed to create pack: {}", e.getMessage());
        }
    }
}