package net.shushi93.resource.client.util;

import net.shushi93.resource.ResourceScreening;
import net.shushi93.resource.client.ResourceScreeningClient;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.file.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class Zip_Helper {
    private static final Logger LOGGER = LoggerFactory.getLogger(ResourceScreening.MOD_ID);

    public static void createPack(String pack_name) {
        Path pack = ResourceScreeningClient.pack_directory.resolve(cleanse(pack_name));
        Map<String, String> env = Map.of("create", "true");

        try (FileSystem fs = FileSystems.newFileSystem(pack, env)) {
            Files.createDirectories(fs.getPath("assets").resolve("minecraft").resolve("textures"));
            Files.writeString(fs.getPath("pack.mcmeta"), """
                    {
                      "pack": {
                        "description": "Generated by Resource Screening",
                        "min_format": [69, 0],
                        "max_format": [2147483647, 0]
                      }
                    }
                    """);
        } catch (Exception e) {
            LoggerFactory.getLogger(ResourceScreening.MOD_ID).error("Failed to create pack: {}", e.getMessage());
        }
    }

    public static @Nullable Collection<String> get_textures(String pack_name) {
        return get_textures(pack_name, false);
    }

    public static @Nullable Collection<String> get_textures(String pack_name, boolean b) {
        Path pack = ResourceScreeningClient.pack_directory.resolve(cleanse(pack_name));
        if (!Files.exists(pack)) {
            LOGGER.error("Pack {} does not exist", pack_name);
            return null;
        }
        try (FileSystem fs = FileSystems.newFileSystem(pack, Map.of())) {
            Path assets = fs.getPath("assets").resolve("minecraft");
            if (!b) assets = assets.resolve("textures");

            try (Stream<Path> pathStream = Files.walk(assets)) {
                return pathStream.filter(Files::isRegularFile)
                        .map(assets::relativize)
                        .map(Path::toString)
                        .collect(Collectors.toCollection(ArrayList::new));
            } catch (Exception e) {
                LOGGER.error(e.getMessage());
            }
        } catch (Exception e) {
            LOGGER.error("Failed to read textures from pack: {}", e.getMessage());
        }
        return null;
    }

    public static @Nullable Collection<String> get_all_pack_names() {
        try (Stream<Path> pathStream = Files.list(ResourceScreeningClient.pack_directory)) {
            return pathStream.map(Path::getFileName)
                    .map(Path::toString)
                    .collect(Collectors.toCollection(ArrayList::new));
        } catch (Exception e) {
            LOGGER.error("Failed to read pack names: {}", e.getMessage());
        }
        return null;
    }

    public static void add_to_pack(String src_pack, String src_path) {
        src_pack = cleanse(src_pack);

        try (FileSystem ds = FileSystems.newFileSystem(
                ResourceScreeningClient.pack_directory.resolve(cleanse("doogile")), Map.of()
        );
             FileSystem fs = FileSystems.newFileSystem(
                     ResourceScreeningClient.pack_directory.resolve(src_pack), Map.of()
             )
        ) {

            if (!Files.exists(ds.getPath("assets", "minecraft", "textures")
                    .resolve(src_path).getParent())) {
                Files.createDirectories(ds.getPath("assets", "minecraft", "textures")
                        .resolve(src_path).getParent());
            }

            Files.copy(fs.getPath("assets", "minecraft", "textures")
                            .resolve(src_path),
                    ds.getPath("assets", "minecraft", "textures")
                            .resolve(src_path),
                    StandardCopyOption.REPLACE_EXISTING);
        } catch (Exception e) {
            LOGGER.error(Arrays.toString(e.getStackTrace()));
        }
    }

    public static void remove_from_pack(String src_path) {
        try (FileSystem fs = FileSystems.newFileSystem(ResourceScreeningClient.pack_directory.resolve(cleanse("doogile")), Map.of())
        ) {
            Files.deleteIfExists(fs.getPath("assets", "minecraft", "textures")
                    .resolve(src_path));
        } catch (Exception e) {
            LOGGER.error(Arrays.toString(e.getStackTrace()));
        }
    }

    private static String cleanse(String pack_name) {
        pack_name = pack_name.startsWith("file/") ? pack_name.substring(5) : pack_name;
        return pack_name.endsWith(".zip") ? pack_name : pack_name + ".zip";
    }
}