package net.shushi93.resource.client.util;

import net.shushi93.resource.ResourceScreening;
import net.shushi93.resource.client.ResourceScreeningClient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class Zip_Helper {

    public static void createPack(String pack_name) {
        Path pack = ResourceScreeningClient.pack_directory.resolve(cleanse(pack_name));
        Map<String, String> env = Map.of("create", "true");

        try (FileSystem fs = FileSystems.newFileSystem(pack, env)) {
            Files.createDirectories(fs.getPath("assets").resolve("minecraft"));
            Files.writeString(fs.getPath("assets").resolve("minecraft").resolve("pack.mcmeta"), """
                    {
                      "pack": {
                        "description": "Generated by Resource Screening",
                        "min_format": [69, 0],
                        "max_format": [2147483647, 0]
                      }
                    }
                    """);
        } catch (Exception e) {
            LoggerFactory.getLogger(ResourceScreening.MOD_ID).error("Failed to create pack: {}", e.getMessage());
        }
    }

    public static void get_textures(String pack_name) {
        get_textures(pack_name, false);
    }

    public static void get_textures(String pack_name, boolean b) {
        Logger logger = LoggerFactory.getLogger(ResourceScreening.MOD_ID);
        pack_name = cleanse(pack_name);
        Path pack = ResourceScreeningClient.pack_directory.resolve(pack_name);
        if (!Files.exists(pack)) {
            logger.error("Pack {} does not exist", pack_name);
            return;
        } else {
            logger.warn("Pack {} exists, attempting to read textures", pack_name);
        }
        try (FileSystem fs = FileSystems.newFileSystem(pack, Map.of())) {
            Path assets = fs.getPath("assets").resolve("minecraft");
            if (b) assets = assets.resolve("textures");
            List<String> arr = Files.walk(assets)
                    .filter(Files::isRegularFile)
                    .map(assets::relativize)
                    .map(Path::toString)
                    .collect(Collectors.toCollection(ArrayList::new));
            logger.debug("Successfully got textures from pack: {}", arr);
        } catch (Exception e) {
            logger.error("Failed to read textures from pack: {}", e.getMessage());
        }
    }

    private static String cleanse(String pack_name) {
        pack_name = pack_name.startsWith("file/") ? pack_name.substring(5) : pack_name;
        return pack_name.endsWith(".zip") ? pack_name : pack_name + ".zip";
    }
}